dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
relation_type_detail:
  type: str
  option: true
secret_level:
  type: str
  option: true
allegiance:
  type: str
  option: true
power_imbalance:
  type: str
  option: true
context:
  type: str
  option: true
