dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
emotional_bond:
  type: str
  option: true
interest_tie:
  type: str
  option: true
karma_weight:
  type: str
  option: true
dependence_level:
  type: str
  option: true
conflict_potential:
  type: str
  option: true
