dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
需要海神之光印记:
  type: str
  option: true
受波塞西监控许可:
  type: str
  option: true
特定时辰或考核阶段开放:
  type: str
  option: true
禁止携带额外魂导器或武器:
  type: str
  option: true
进入需通过守护者测试:
  type: str
  option: true
