dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
能量稳定度:
  type: str
  option: true
深渊渗透程度（黑化小舞影响）:
  type: str
  option: true
考核激活状态:
  type: str
  option: true
当前天气影响:
  type: str
  option: true
结界封印强度:
  type: str
  option: true
