dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
mythical_causality:
  type: str
  option: true
prophecy_link:
  type: str
  option: true
temporal_marker:
  type: str
  option: true
spatial_context:
  type: str
  option: true
fate_class:
  type: str
  option: true
