dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
divine_origin:
  type: str
  option: true
karmic_weight:
  type: str
  option: true
transformation_catalyst:
  type: str
  option: true
social_power:
  type: str
  option: true
emotional_bond:
  type: str
  option: true
