dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
blood_status_required:
  type: str
  option: true
password_required:
  type: str
  option: true
patrolled_by_carros:
  type: str
  option: true
secret_entrance_available:
  type: str
  option: true
time_restrictions:
  type: str
  option: true
cleansing_certificate_required:
  type: str
  option: true
monitoring_spells_active:
  type: str
  option: true
