dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
secret_entry:
  type: str
  option: true
monitored_end:
  type: str
  option: true
alternate_end:
  type: str
  option: true
guard_post_nearby:
  type: str
  option: true
