dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
secret_name:
  type: str
  option: true
faction:
  type: str
  option: true
is_known_to_enemy:
  type: str
  option: true
historical_significance:
  type: str
  option: true
