dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
relation_type_specific:
  type: str
  option: true
historical_event:
  type: str
  option: true
trust_level:
  type: str
  option: true
