dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
alliance_form:
  type: str
  option: true
kinship_type:
  type: str
  option: true
diplomatic_status:
  type: str
  option: true
