dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
invisibility_required:
  type: str
  option: true
under_surveillance:
  type: str
  option: true
alarm_trigger:
  type: str
  option: true
pass_demanded:
  type: str
  option: true
disillusionment_charm_active:
  type: str
  option: true
restricted_hours_usage:
  type: str
  option: true
