dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
hidden_door:
  type: str
  option: true
password_required:
  type: str
  option: true
one_way_blocked:
  type: str
  option: true
guarded_entrance:
  type: str
  option: true
requires_magical_trigger:
  type: str
  option: true
