dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
faction:
  type: str
  option: true
hidden_identity:
  type: str
  option: true
house:
  type: str
  option: true
blood_status:
  type: str
  option: true
cover_role:
  type: str
  option: true
