dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
loyalty_dynamic:
  type: str
  option: true
fear_level:
  type: str
  option: true
moral_boundary:
  type: str
  option: true
suspicion_index:
  type: str
  option: true
resilience:
  type: str
  option: true
