dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
faction_reputation:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
codename:
  type: str
  option: true
trust_circle:
  type: str
  option: true
public_perception:
  type: str
  option: true
