dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
password_required:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
alarm_system:
  type: str
  option: true
death_eater_patrol:
  type: str
  option: true
