dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
birth_family:
  type: str
  option: true
status_level:
  type: str
  option: true
name_symbolism:
  type: str
  option: true
karma_tag:
  type: str
  option: true
