dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
cat_communication:
  type: str
  option: true
stone_reading:
  type: str
  option: true
reality_blurring_vision:
  type: str
  option: true
