dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
fate_fulfillment_goal:
  type: str
  option: true
escape_from_curse:
  type: str
  option: true
spiritual_enlightenment:
  type: str
  option: true
