dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
supernatural_identity_marker:
  type: str
  option: true
cursed_by_fate:
  type: str
  option: true
fragmented_memory_indicator:
  type: str
  option: true
