dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
fragmented_memory_pieces:
  type: str
  option: true
surreal_knowledge_of_stone:
  type: str
  option: true
drenched_with_fate:
  type: str
  option: true
