dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
philosophical_reflection_tendency:
  type: str
  option: true
surreal_perception:
  type: str
  option: true
existential_anxiety:
  type: str
  option: true
