dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
required_token:
  type: str
  option: true
guard_type:
  type: str
  option: true
unlock_condition:
  type: str
  option: true
teleport_array:
  type: str
  option: true
banishment_proof:
  type: str
  option: true
