dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
spatial_hierarchy:
  type: str
  option: true
celestial_bureau:
  type: str
  option: true
restriction_level:
  type: str
  option: true
associated_event:
  type: str
  option: true
mythical_significance:
  type: str
  option: true
