dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
requires_emotional_state:
  type: str
  option: true
time_restriction:
  type: str
  option: true
weather_condition:
  type: str
  option: true
spatial_anomaly:
  type: str
  option: true
