dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
special_ability:
  type: str
  option: true
leadership_ability:
  type: str
  option: true
political_ability:
  type: str
  option: true
