dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
key_life_turning_point:
  type: str
  option: true
important_ally_enemy_memory:
  type: str
  option: true
