dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
requires_solitude:
  type: str
  option: true
secret_entrance_condition:
  type: str
  option: true
supernatural_gateway:
  type: str
  option: true
restricted_to_certain_roles:
  type: str
  option: true
emotional_prerequisite:
  type: str
  option: true
