dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
temporal_anomaly:
  type: str
  option: true
material_instability:
  type: str
  option: true
ambient_feeling:
  type: str
  option: true
supernatural_activity_level:
  type: str
  option: true
metaphysical_cycle:
  type: str
  option: true
