dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
soul_power_suppression_level:
  type: str
  option: true
emotional_trial_required:
  type: str
  option: true
time_limit_seconds:
  type: str
  option: true
abyss_corruption_level:
  type: str
  option: true
requires_karma_pass:
  type: str
  option: true
