dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
unlock_condition:
  type: str
  option: true
is_hidden:
  type: str
  option: true
directional_restriction:
  type: str
  option: true
temporal_availability:
  type: str
  option: true
