dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
goal_for_summit:
  type: str
  option: true
stance_on_akatsuki:
  type: str
  option: true
personal_ambition:
  type: str
  option: true
