dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
loyalty:
  type: str
  option: true
ambition:
  type: str
  option: true
caution:
  type: str
  option: true
emotional_expression:
  type: str
  option: true
