dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
organization_rank:
  type: str
  option: true
fame:
  type: str
  option: true
social_network:
  type: str
  option: true
bounty:
  type: str
  option: true
