dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
password_required:
  type: str
  option: true
special_permission_required:
  type: str
  option: true
magical_barrier_type:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
secret_entry_available:
  type: str
  option: true
patrol_frequency:
  type: str
  option: true
