dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
usage_status:
  type: str
  option: true
maintenance_condition:
  type: str
  option: true
defensive_spells:
  type: str
  option: true
lighting_condition:
  type: str
  option: true
curse_status:
  type: str
  option: true
occupancy_status:
  type: str
  option: true
