dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
restricted_access_description:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
