dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
critical_memory_fragments:
  type: str
  option: true
faction_alignment_history:
  type: str
  option: true
