dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
affiliation:
  type: str
  option: true
title:
  type: str
  option: true
reputation_details:
  type: str
  option: true
