dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
kinship_type:
  type: str
  option: true
political_marriage_flag:
  type: str
  option: true
master_servant_role:
  type: str
  option: true
love_type:
  type: str
  option: true
power_chain_rank:
  type: str
  option: true
gender_restriction_level:
  type: str
  option: true
