dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
pass_required:
  type: str
  option: true
rank_restriction:
  type: str
  option: true
night_travel_allowed:
  type: str
  option: true
weather_vulnerability:
  type: str
  option: true
hostile_threat_level:
  type: str
  option: true
trap_density:
  type: str
  option: true
special_ability_needed:
  type: str
  option: true
time_window:
  type: str
  option: true
