dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
distance_km:
  type: str
  option: true
checkpoints:
  type: str
  option: true
passes_neutral_territory:
  type: str
  option: true
pilgrimage_route:
  type: str
  option: true
trade_cities:
  type: str
  option: true
