name: WorldKernelActions
components:
  communication:
    plugins:
      WKCommunicationPlugin: {}
  move:
    plugins:
      WKMovePlugin: {}
  otheractions:
    plugins:
      WKOtherActionPlugin: {}
