dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
surveillance_level:
  type: str
  option: true
password_required:
  type: str
  option: true
alarm_charms:
  type: str
  option: true
entry_restrictions_by_faction:
  type: str
  option: true
cursed_entries:
  type: str
  option: true
