dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
safety_level:
  type: str
  option: true
hidden_passages:
  type: str
  option: true
dark_magic_contamination:
  type: str
  option: true
resistance_activity_use:
  type: str
  option: true
historical_event_marker:
  type: str
  option: true
