dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
hidden_functionality:
  type: str
  option: true
damage_level:
  type: str
  option: true
soul_fragment_influence:
  type: str
  option: true
prisoner_hideout:
  type: str
  option: true
functional_alteration_by_deatheaters:
  type: str
  option: true
