dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
surface_material:
  type: str
  option: true
has_restriction:
  type: str
  option: true
connected_to_vein:
  type: str
  option: true
transformable:
  type: str
  option: true
