dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
visiting_hours:
  type: str
  option: true
entry_ritual:
  type: str
  option: true
seasonal_availability:
  type: str
  option: true
social_restrictions:
  type: str
  option: true
psychological_barrier:
  type: str
  option: true
