dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
emotional_aura:
  type: str
  option: true
associated_characters:
  type: str
  option: true
historical_period:
  type: str
  option: true
narrative_significance:
  type: str
  option: true
symbolic_theme:
  type: str
  option: true
