dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
atmospheric_condition:
  type: str
  option: true
occupancy_rate:
  type: str
  option: true
maintenance_level:
  type: str
  option: true
temporal_phase:
  type: str
  option: true
weather_affinity:
  type: str
  option: true
