dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
game_skills:
  type: str
  option: true
knowledge_systems:
  type: str
  option: true
rule_understanding_level:
  type: str
  option: true
resistance_tendency:
  type: str
  option: true
