dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
memory_retention_status:
  type: str
  option: true
appearance_token:
  type: str
  option: true
original_name_hash:
  type: str
  option: true
