dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
fear_level:
  type: str
  option: true
determination:
  type: str
  option: true
madness_level:
  type: str
  option: true
suspicion_tendency:
  type: str
  option: true
