dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
trust_network:
  type: str
  option: true
alliance_status:
  type: str
  option: true
memory_sharing_group_id:
  type: str
  option: true
