dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
jazz_appreciation:
  type: str
  option: true
american_literature_knowledge:
  type: str
  option: true
loneliness_endurance:
  type: str
  option: true
conversation_strip_skill:
  type: str
  option: true
