dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
meaningless_action_tendency:
  type: str
  option: true
escape_desire:
  type: str
  option: true
nostalgia_fixation:
  type: str
  option: true
self_discovery_through_others:
  type: str
  option: true
