dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
age_range:
  type: str
  option: true
cultural_reference:
  type: str
  option: true
summer_detail:
  type: str
  option: true
secret_story:
  type: str
  option: true
