dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
encounter_type:
  type: str
  option: true
friendship_depth:
  type: str
  option: true
family_distance:
  type: str
  option: true
memory_bond_level:
  type: str
  option: true
emotional_temperature:
  type: str
  option: true
