dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
surveillance_level:
  type: str
  option: true
is_hidden:
  type: str
  option: true
access_limit_per_day:
  type: str
  option: true
code_name:
  type: str
  option: true
zone_id:
  type: str
  option: true
camouflage_type:
  type: str
  option: true
