dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
escape_school_priority:
  type: str
  option: true
protect_fellow_students:
  type: str
  option: true
undermine_carregime:
  type: str
  option: true
survival_over_honor:
  type: str
  option: true
