dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
loyalty_bias:
  type: str
  option: true
fear_of_carous:
  type: str
  option: true
secret_resistance_urge:
  type: str
  option: true
trust_threshold:
  type: str
  option: true
