dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
is_secret_passage:
  type: str
  option: true
known_by_faction:
  type: str
  option: true
detection_risk_level:
  type: str
  option: true
historical_significance:
  type: str
  option: true
