dim_name: PropertiesDim
distance:
  type: str
travel_time:
  type: str
visibility:
  type: str
is_magical:
  type: str
  option: true
requires_invisibility_cloak:
  type: str
  option: true
monitored_by_spells:
  type: str
  option: true
mobility_restriction:
  type: str
  option: true
