dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
curfew_status:
  type: str
  option: true
password_required:
  type: str
  option: true
danger_level:
  type: str
  option: true
lock_type:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
