dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
safety_level:
  type: str
  option: true
magical_barrier:
  type: str
  option: true
current_activity:
  type: str
  option: true
damage_level:
  type: str
  option: true
residual_magic:
  type: str
  option: true
