dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
forbidden_magic_knowledge:
  type: str
  option: true
underground_communication_skill:
  type: str
  option: true
combat_experience:
  type: str
  option: true
interrogation_resistance:
  type: str
  option: true
