dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
war_stance:
  type: str
  option: true
public_allegiance:
  type: str
  option: true
hidden_identity:
  type: str
  option: true
group_role_in_resistance:
  type: str
  option: true
