dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
witnessed_atrocity:
  type: str
  option: true
preexisting_punishment_record:
  type: str
  option: true
known_death_eater_secrets:
  type: str
  option: true
memory_modified_incident:
  type: str
  option: true
