dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
time_restriction:
  type: str
  option: true
curse_protection:
  type: str
  option: true
patrol_frequency:
  type: str
  option: true
password:
  type: str
  option: true
is_monitored:
  type: str
  option: true
magical_ward:
  type: str
  option: true
requires_permission:
  type: str
  option: true
noise_check:
  type: str
  option: true
