dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
secret_exit:
  type: str
  option: true
monitored:
  type: str
  option: true
requires_communication:
  type: str
  option: true
hidden_entrance:
  type: str
  option: true
connected_to_secret_room:
  type: str
  option: true
