dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
discovered_by:
  type: str
  option: true
used_for:
  type: str
  option: true
alias:
  type: str
  option: true
secret_passage:
  type: str
  option: true
historical_significance:
  type: str
  option: true
