dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
requires_password:
  type: str
  option: true
requires_specific_item:
  type: str
  option: true
is_monitored:
  type: str
  option: true
has_threshold_enchantment:
  type: str
  option: true
