dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
magical_specialization:
  type: str
  option: true
occlumency_level:
  type: str
  option: true
legilimency_resistance:
  type: str
  option: true
dark_arts_proficiency:
  type: str
  option: true
animagus_form:
  type: str
  option: true
patronus_type:
  type: str
  option: true
