dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
known_horcrux_locations:
  type: str
  option: true
critical_secret_events:
  type: str
  option: true
recent_encounter_log:
  type: str
  option: true
betrayal_memory_flag:
  type: str
  option: true
trust_rating_towards_others:
  type: str
  option: true
