dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
psychological_state:
  type: str
  option: true
loyalty_level:
  type: str
  option: true
rebellious_tendency:
  type: str
  option: true
paranoia_index:
  type: str
  option: true
