dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_disguise:
  type: str
  option: true
safety_level:
  type: str
  option: true
emotional_arousal:
  type: str
  option: true
under_surveillance:
  type: str
  option: true
