dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
entry_ritual:
  type: str
  option: true
weather_requirement:
  type: str
  option: true
time_of_day_requirement:
  type: str
  option: true
psychic_state_requirement:
  type: str
  option: true
invisible_guardian:
  type: str
  option: true
