dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
cover_story:
  type: str
  option: true
suspicion_level:
  type: str
  option: true
pureblood_standing:
  type: str
  option: true
relative_influence:
  type: str
  option: true
