dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
monitored_by:
  type: str
  option: true
connects_to_restricted_area:
  type: str
  option: true
escape_route_for_resistance:
  type: str
  option: true
traverses_house_territory:
  type: str
  option: true
