dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
security_level:
  type: str
  option: true
hidden_feature:
  type: str
  option: true
atmosphere:
  type: str
  option: true
is_secret_passage:
  type: str
  option: true
requires_permit:
  type: str
  option: true
