dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
underground_reputation:
  type: str
  option: true
suspicion_level:
  type: str
  option: true
house_point_standing:
  type: str
  option: true
death_eater_trust_level:
  type: str
  option: true
