dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
previous_life_role:
  type: str
  option: true
mortal_mission:
  type: str
  option: true
karmic_symbol:
  type: str
  option: true
celestial_registry:
  type: str
  option: true
