dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
previous_life_memory_segment:
  type: str
  option: true
prophetic_dream_content:
  type: str
  option: true
hidden_truth_fragment:
  type: str
  option: true
forgotten_encounter_record:
  type: str
  option: true
