dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
celestial_rank_title:
  type: str
  option: true
mortal_class_marker:
  type: str
  option: true
fate_label:
  type: str
  option: true
karma_reputation:
  type: str
  option: true
