dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
spatial_realm_type:
  type: str
  option: true
temporal_event_marker:
  type: str
  option: true
memory_seal_level:
  type: str
  option: true
transformation_phase:
  type: str
  option: true
