dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
functional_alteration_type:
  type: str
  option: true
physical_condition:
  type: str
  option: true
hidden_content_flag:
  type: str
  option: true
atmosphere_gauge:
  type: str
  option: true
alarm_magic_activation:
  type: str
  option: true
occupancy_trend:
  type: str
  option: true
