dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
hidden_passage_exists:
  type: str
  option: true
surveillance_density:
  type: str
  option: true
patrol_frequency:
  type: str
  option: true
key_or_permission_required:
  type: str
  option: true
