dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
associated_game_rules:
  type: str
  option: true
danger_level:
  type: str
  option: true
location_function:
  type: str
  option: true
secret_room_indicator:
  type: str
  option: true
