name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
magical_specialty:
  type: str
  option: true
exceptional_ability:
  type: str
  option: true
forbidden_arts_proficiency:
  type: str
  option: true
known_patronus:
  type: str
  option: true
