name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
inner_circle_trust:
  type: str
  option: true
relative_network:
  type: str
  option: true
spy_affiliation:
  type: str
  option: true
house_alliance:
  type: str
  option: true
