dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
current_exam_sub_goal:
  type: str
  option: true
hidden_agenda:
  type: str
  option: true
emotional_breakthrough_target:
  type: str
  option: true
