dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
critical_exam_memories:
  type: str
  option: true
memory_of_loved_ones:
  type: str
  option: true
hidden_trauma_or_secret:
  type: str
  option: true
