dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
faith_in_sea_god:
  type: str
  option: true
reaction_to_crisis:
  type: str
  option: true
emotional_attachment_style:
  type: str
  option: true
