dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
reputation_in_sea_god_island:
  type: str
  option: true
relation_with_seven_pillars:
  type: str
  option: true
internal_faction_standing:
  type: str
  option: true
