dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
access_scope:
  type: str
  option: true
gender_restriction:
  type: str
  option: true
time_restriction:
  type: str
  option: true
special_event_access:
  type: str
  option: true
