dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
belongs_to_estate:
  type: str
  option: true
symbolic_meaning:
  type: str
  option: true
key_plot_events:
  type: str
  option: true
literary_imagery:
  type: str
  option: true
