dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
password_required:
  type: str
  option: true
time_restriction:
  type: str
  option: true
item_required:
  type: str
  option: true
protective_enchantments:
  type: str
  option: true
blood_status_restriction:
  type: str
  option: true
invisibility_required:
  type: str
  option: true
