dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
house_affiliation:
  type: str
  option: true
historical_significance:
  type: str
  option: true
magical_features:
  type: str
  option: true
aliases:
  type: str
  option: true
is_forbidden_area:
  type: str
  option: true
founder_associated:
  type: str
  option: true
