dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
affiliated_village:
  type: str
  option: true
geographic_region:
  type: str
  option: true
security_level:
  type: str
  option: true
historical_significance:
  type: str
  option: true
