dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
occupation_status:
  type: str
  option: true
maintenance_condition:
  type: str
  option: true
current_event:
  type: str
  option: true
