dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
literary_composition_skill:
  type: str
  option: true
painting_or_calligraphy_skill:
  type: str
  option: true
music_or_dance_skill:
  type: str
  option: true
domestic_management_ability:
  type: str
  option: true
medical_or_herbal_knowledge:
  type: str
  option: true
strategic_maneuvering:
  type: str
  option: true
reading_proficiency_for_women:
  type: str
  option: true
