dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
jinling_twelve_belles_prophesied_fate:
  type: str
  option: true
marriage_alliance_target:
  type: str
  option: true
clan_restoration_ambition:
  type: str
  option: true
escape_or_reform_of_oppression:
  type: str
  option: true
protection_of_certain_family_members:
  type: str
  option: true
