dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
family_generation:
  type: str
  option: true
noble_rank_or_official_title:
  type: str
  option: true
jinling_twelve_belles_catalogue:
  type: str
  option: true
fate_couplet:
  type: str
  option: true
lineage_position:
  type: str
  option: true
palace_title_if_applicable:
  type: str
  option: true
marital_status:
  type: str
  option: true
dowry_or_estate_inheritance:
  type: str
  option: true
