dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
memory_of_imperial_consort_shengqin:
  type: str
  option: true
key_poem_society_events:
  type: str
  option: true
childhood_interactions_with_cousins:
  type: str
  option: true
secret_knowledge_of_family_corruption:
  type: str
  option: true
traumatic_experiences:
  type: str
  option: true
seasonal_festival_memories:
  type: str
  option: true
