dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
standing_in_rong_ning_houses:
  type: str
  option: true
reputation_among_servants:
  type: str
  option: true
alliance_with_other_noble_families:
  type: str
  option: true
appraisal_by_elder_matrons:
  type: str
  option: true
criticized_or_admired_by_peers:
  type: str
  option: true
role_in_family_power_structure:
  type: str
  option: true
