dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_courtyard_residence:
  type: str
  option: true
physical_health_condition:
  type: str
  option: true
emotional_mood_state:
  type: str
  option: true
current_activity_or_seasonal_event:
  type: str
  option: true
indoors_or_outdoors_restriction:
  type: str
  option: true
time_of_day_and_schedule:
  type: str
  option: true
