dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
occlumency_mastery:
  type: str
  option: true
defense_against_dark_arts_proficiency:
  type: str
  option: true
transfiguration_specialization:
  type: str
  option: true
legilimency_resistance:
  type: str
  option: true
horcrux_knowledge:
  type: str
  option: true
forbidden_spells_knowledge:
  type: str
  option: true
