dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
horcrux_hunt_target:
  type: str
  option: true
intelligence_gathering_objective:
  type: str
  option: true
survival_priority:
  type: str
  option: true
resistance_communication_duty:
  type: str
  option: true
ward_bypass_objective:
  type: str
  option: true
