dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
faction:
  type: str
  option: true
disguise_identity:
  type: str
  option: true
dark_mark_present:
  type: str
  option: true
order_of_phoenix_rank:
  type: str
  option: true
death_eater_affiliation_level:
  type: str
  option: true
