dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
resistance_group_role:
  type: str
  option: true
suspicion_level:
  type: str
  option: true
informant_tag:
  type: str
  option: true
neutrality_credibility:
  type: str
  option: true
familial_vulnerability:
  type: str
  option: true
