dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_alertness:
  type: str
  option: true
hidden_status:
  type: str
  option: true
injury_severity:
  type: str
  option: true
magic_residue_detection_risk:
  type: str
  option: true
under_surveillance:
  type: str
  option: true
