dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
relationship_duration:
  type: str
  option: true
public_perception:
  type: str
  option: true
resistance_affiliation:
  type: str
  option: true
punishment_risk:
  type: str
  option: true
emotional_tone:
  type: str
  option: true
power_dynamic:
  type: str
  option: true
