dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
ability_proficiency:
  type: str
  option: true
combat_style:
  type: str
  option: true
ability_side_effects:
  type: str
  option: true
energy_consumption_rate:
  type: str
  option: true
special_ability_synergy:
  type: str
  option: true
