dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
suppressed_memories:
  type: str
  option: true
memory_access_level:
  type: str
  option: true
emotional_charge:
  type: str
  option: true
shared_memory_trauma:
  type: str
  option: true
memory_integrity:
  type: str
  option: true
