dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
trust_level:
  type: str
  option: true
social_role_in_group:
  type: str
  option: true
factional_stance:
  type: str
  option: true
reputation_tier:
  type: str
  option: true
information_clearance_level:
  type: str
  option: true
