dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
health_status:
  type: str
  option: true
ability_overload_level:
  type: str
  option: true
current_action_state:
  type: str
  option: true
fatigue_level:
  type: str
  option: true
ability_cooldown_remaining:
  type: str
  option: true
