dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
trust_level:
  type: str
  option: true
shared_secrets:
  type: str
  option: true
conflict_intensity:
  type: str
  option: true
external_pressure:
  type: str
  option: true
loyalty_conflict:
  type: str
  option: true
