dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
rain_trigger:
  type: str
  option: true
sleep_required:
  type: str
  option: true
cat_mediation:
  type: str
  option: true
trauma_threshold:
  type: str
  option: true
