dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
symbolic_meaning:
  type: str
  option: true
threshold_nature:
  type: str
  option: true
morph_property:
  type: str
  option: true
