dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
power_dynamics:
  type: str
  option: true
communication_pattern:
  type: str
  option: true
emotional_dependence_level:
  type: str
  option: true
trauma_sharing:
  type: str
  option: true
physical_intimacy_level:
  type: str
  option: true
future_prospect:
  type: str
  option: true
parallel_to_other_relationship:
  type: str
  option: true
class_difference:
  type: str
  option: true
age_gap:
  type: str
  option: true
shared_interest:
  type: str
  option: true
