dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
password:
  type: str
  option: true
identification_method:
  type: str
  option: true
requires_invisibility:
  type: str
  option: true
special_exemption:
  type: str
  option: true
