dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
secret_name:
  type: str
  option: true
passage_type:
  type: str
  option: true
is_under_surveillance:
  type: str
  option: true
has_been_tampered:
  type: str
  option: true
