dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
trust_level:
  type: str
  option: true
public_knowledge:
  type: str
  option: true
conflict_potential:
  type: str
  option: true
