dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
access_time_restriction:
  type: str
  option: true
person_type_restriction:
  type: str
  option: true
weather_impact:
  type: str
  option: true
maintenance_state:
  type: str
  option: true
seasonal_variation:
  type: str
  option: true
