dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
connects_inner_outer:
  type: str
  option: true
connects_hierarchy_zones:
  type: str
  option: true
connects_scenic_spots:
  type: str
  option: true
