dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
path_name:
  type: str
  option: true
path_function:
  type: str
  option: true
cultural_connotation:
  type: str
  option: true
