dim_name: PropertiesDim
distance:
  type: str
travel_time:
  type: str
visibility:
  type: str
paving_material:
  type: str
  option: true
width:
  type: str
  option: true
has_cover:
  type: str
  option: true
has_gate:
  type: str
  option: true
has_lantern:
  type: str
  option: true
has_decoration:
  type: str
  option: true
