dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
seasonal_state:
  type: str
  option: true
atmosphere:
  type: str
  option: true
temporal_markers:
  type: str
  option: true
functional_cycle:
  type: str
  option: true
