dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
power_dynamics:
  type: str
  option: true
secret_contact:
  type: str
  option: true
loyalty_based:
  type: str
  option: true
monitoring_role:
  type: str
  option: true
allegiance_type:
  type: str
  option: true
