dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
trust_level:
  type: str
  option: true
collaboration_type:
  type: str
  option: true
risk_level:
  type: str
  option: true
frequency:
  type: str
  option: true
emotional_tone:
  type: str
  option: true
