dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
from_area_type:
  type: str
  option: true
to_area_type:
  type: str
  option: true
from_security_level:
  type: str
  option: true
to_security_level:
  type: str
  option: true
hidden_endpoint:
  type: str
  option: true
transport_type:
  type: str
  option: true
