dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
current_password:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
patrol_frequency:
  type: str
  option: true
forbidden_charm_ward:
  type: str
  option: true
secret_entrance_hint:
  type: str
  option: true
floo_network_allowed:
  type: str
  option: true
portkey_activation:
  type: str
  option: true
