dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
code_name:
  type: str
  option: true
alternate_names:
  type: str
  option: true
horcrux_related:
  type: str
  option: true
danger_rating:
  type: str
  option: true
historical_significance:
  type: str
  option: true
dark_magic_resonance:
  type: str
  option: true
