dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
death_eater_affiliation:
  type: str
  option: true
relationships_with_key_figures:
  type: str
  option: true
house_reputation:
  type: str
  option: true
