dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
status_in_school:
  type: str
  option: true
current_location_description:
  type: str
  option: true
