dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
password_required:
  type: str
  option: true
surveillance_charm:
  type: str
  option: true
anti_apparition:
  type: str
  option: true
anti_tracking:
  type: str
  option: true
restricted_to_faction:
  type: str
  option: true
ward_level:
  type: str
  option: true
