dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
secret_mission:
  type: str
  option: true
person_to_protect:
  type: str
  option: true
target_to_eliminate:
  type: str
  option: true
information_to_obtain:
  type: str
  option: true
