dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
traumatic_memories:
  type: str
  option: true
knowledge_of_horcruxes:
  type: str
  option: true
knowledge_of_deathly_hallows:
  type: str
  option: true
cursed_wound_related_memory:
  type: str
  option: true
