dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
loyalty_to_voldemort:
  type: str
  option: true
willingness_to_betray:
  type: str
  option: true
courage_level:
  type: str
  option: true
paranoia_level:
  type: str
  option: true
trust_in_others:
  type: str
  option: true
