dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
membership_in_organizations:
  type: str
  option: true
trust_level:
  type: str
  option: true
intimidation_factor:
  type: str
  option: true
popularity:
  type: str
  option: true
