dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
under_surveillance:
  type: str
  option: true
current_disguise:
  type: str
  option: true
health_status:
  type: str
  option: true
holds_horcrux_fragment:
  type: str
  option: true
