dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
from_faction_control:
  type: str
  option: true
to_faction_control:
  type: str
  option: true
has_surveillance_post:
  type: str
  option: true
same_house_region:
  type: str
  option: true
