dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
secret_route:
  type: str
  option: true
requires_password:
  type: str
  option: true
password:
  type: str
  option: true
associated_map:
  type: str
  option: true
one_way_if_condition:
  type: str
  option: true
escape_route:
  type: str
  option: true
blocked_by_enemy:
  type: str
  option: true
