dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
hidden:
  type: str
  option: true
monitored:
  type: str
  option: true
magical_properties:
  type: str
  option: true
requires_magic:
  type: str
  option: true
known_to_resistance:
  type: str
  option: true
known_to_death_eaters:
  type: str
  option: true
