dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
allegiance_clash:
  type: str
  option: true
trust_level:
  type: str
  option: true
secret_alliance:
  type: str
  option: true
surveillance_aspect:
  type: str
  option: true
power_dynamic:
  type: str
  option: true
emotional_connection:
  type: str
  option: true
information_channel:
  type: str
  option: true
historical_relation:
  type: str
  option: true
