dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
backstory_impact:
  type: str
  option: true
current_tension:
  type: str
  option: true
hidden_motives:
  type: str
  option: true
loyalty_timeline:
  type: str
  option: true
resistance_involvement:
  type: str
  option: true
blood_status_influence:
  type: str
  option: true
