dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
join_dark_side_goal:
  type: str
  option: true
protect_someone_goal:
  type: str
  option: true
horcrux_hunt_goal:
  type: str
  option: true
intel_gathering_goal:
  type: str
  option: true
survival_priority_goal:
  type: str
  option: true
