dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
memory_of_dumbledore_death:
  type: str
  option: true
memory_of_betrayal:
  type: str
  option: true
secret_passage_knowledge:
  type: str
  option: true
room_of_requirement_hidden_room_knowledge:
  type: str
  option: true
death_eater_plan_knowledge:
  type: str
  option: true
