dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
attitude_to_authority:
  type: str
  option: true
secretive_tendency:
  type: str
  option: true
loyalty_behavior:
  type: str
  option: true
trauma_exposure:
  type: str
  option: true
duality_persona:
  type: str
  option: true
