dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_concealment_status:
  type: str
  option: true
under_surveillance:
  type: str
  option: true
health_status:
  type: str
  option: true
wand_in_hand:
  type: str
  option: true
dark_mark_marking:
  type: str
  option: true
