dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
secret_passage:
  type: str
  option: true
surveillance_level:
  type: str
  option: true
atmosphere_description:
  type: str
  option: true
associated_resistance_network:
  type: str
  option: true
