dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
intermediate_stops:
  type: str
  option: true
distance_category:
  type: str
  option: true
strategic_importance:
  type: str
  option: true
