dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
controlled_by:
  type: str
  option: true
connects_to_cities:
  type: str
  option: true
route_type:
  type: str
  option: true
historical_name:
  type: str
  option: true
is_famous_route:
  type: str
  option: true
