dim_name: PropertiesDim
distance:
  type: str
travel_time:
  type: str
visibility:
  type: str
terrain_type:
  type: str
  option: true
seasonal_impact:
  type: str
  option: true
ambush_suitability:
  type: str
  option: true
supply_difficulty:
  type: str
  option: true
water_source_availability:
  type: str
  option: true
