dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
instrument_playing_skill:
  type: str
  option: true
writing_ability:
  type: str
  option: true
coping_mechanism:
  type: str
  option: true
alcohol_tolerance:
  type: str
  option: true
psychotherapy_receptiveness:
  type: str
  option: true
memory_vividness:
  type: str
  option: true
