dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
memory_of_deceased_person:
  type: str
  option: true
memory_of_specific_well:
  type: str
  option: true
memory_of_amibe_sanatorium:
  type: str
  option: true
music_associated_memory:
  type: str
  option: true
traumatic_recollection:
  type: str
  option: true
childhood_attachment_memory:
  type: str
  option: true
