dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
inner_monologue_tendency:
  type: str
  option: true
attitude_toward_death:
  type: str
  option: true
attitude_toward_suicide:
  type: str
  option: true
music_taste:
  type: str
  option: true
loneliness_intensity:
  type: str
  option: true
social_avoidance_level:
  type: str
  option: true
nostalgia_frequency:
  type: str
  option: true
