dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
group_affiliation:
  type: str
  option: true
reputation_label:
  type: str
  option: true
emotional_dependency_object:
  type: str
  option: true
circle_of_trust:
  type: str
  option: true
stigma_related_to_trauma:
  type: str
  option: true
