dim_name: EndpointsDim
from_id:
  type: str
  ref: location
to_id:
  type: str
  ref: location
bidirectional:
  type: bool
seasonal_variation:
  type: str
  option: true
lighting_condition:
  type: str
  option: true
soundscape:
  type: str
  option: true
