dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
atmosphere_description:
  type: str
  option: true
time_period_feel:
  type: str
  option: true
cultural_reference:
  type: str
  option: true
