dim_name: PropertiesDim
distance:
  type: str
travel_time:
  type: str
visibility:
  type: str
lighting_condition:
  type: str
  option: true
noise_level:
  type: str
  option: true
magical_ward:
  type: str
  option: true
is_spider_infested:
  type: str
  option: true
dimensional_stability:
  type: str
  option: true
