dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
combat_skills:
  type: str
  option: true
espionage_skills:
  type: str
  option: true
resistance_experience:
  type: str
  option: true
knowledge_of_secret_passage:
  type: str
  option: true
magical_abilities:
  type: str
  option: true
danger_awareness:
  type: str
  option: true
