dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
priority:
  type: str
  option: true
risk_tolerance:
  type: str
  option: true
sacrifice_willingness:
  type: str
  option: true
primary_loyalty:
  type: str
  option: true
