dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
public_identity:
  type: str
  option: true
true_allegiance:
  type: str
  option: true
blood_status:
  type: str
  option: true
house:
  type: str
  option: true
cover_story:
  type: str
  option: true
known_affiliation:
  type: str
  option: true
