dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
traumatic_memories:
  type: str
  option: true
loyalty_oaths:
  type: str
  option: true
hidden_knowledge:
  type: str
  option: true
moral_conflicts:
  type: str
  option: true
information_sources:
  type: str
  option: true
