dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
belongs_to_household:
  type: str
  option: true
path_type:
  type: str
  option: true
is_inside_garden:
  type: str
  option: true
hierarchy_rank:
  type: str
  option: true
connected_courtyard:
  type: str
  option: true
