dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
cat_telepathy:
  type: str
  option: true
boundary_crossing_ability:
  type: str
  option: true
dream_weaving:
  type: str
  option: true
historical_echo_hearing:
  type: str
  option: true
portal_recognition:
  type: str
  option: true
