dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
escape_prophecy:
  type: str
  option: true
seek_truth_of_curse:
  type: str
  option: true
encounter_phantom_figure:
  type: str
  option: true
reconcile_past_wounds:
  type: str
  option: true
achieve_self_redemption:
  type: str
  option: true
