dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
symbolic_name:
  type: str
  option: true
curse_bearer:
  type: str
  option: true
supernatural_origin:
  type: str
  option: true
shadow_self:
  type: str
  option: true
mother_sister_incarnation:
  type: str
  option: true
