dim_name: PersonalityDim
traits:
  type: list_str
values:
  type: list_str
speech_style:
  type: str
introspective_silence:
  type: str
  option: true
fatalistic_acceptance:
  type: str
  option: true
duality_nature:
  type: str
  option: true
metaphorical_speech_tendency:
  type: str
  option: true
trauma_repression:
  type: str
  option: true
