dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
symbolic_role_in_cosmos:
  type: str
  option: true
phantom_connection_degree:
  type: str
  option: true
animal_community_rel:
  type: str
  option: true
historical_figure_echo:
  type: str
  option: true
taboo_group_membership:
  type: str
  option: true
