dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
social_hierarchy_level:
  type: str
  option: true
specific_access_rules:
  type: str
  option: true
ceremonial_use_restriction:
  type: str
  option: true
seasonal_access_conditions:
  type: str
  option: true
