dim_name: IdentityDim
id:
  type: str
name:
  type: str
type:
  type: str
description:
  type: str
symbolic_meaning:
  type: str
  option: true
associated_plot_events:
  type: str
  option: true
historical_literary_reference:
  type: str
  option: true
custom_function:
  type: str
  option: true
