dim_name: AccessDim
permissions:
  type: str
access_level:
  type: str
access_conditions:
  type: str
curfew_applies:
  type: str
  option: true
required_password_or_charm:
  type: str
  option: true
patrolled_by_deatheaters:
  type: str
  option: true
restricted_hours:
  type: str
  option: true
emergency_exit_available:
  type: str
  option: true
