dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
physical_integrity:
  type: str
  option: true
magical_ward_status:
  type: str
  option: true
functional_alteration:
  type: str
  option: true
current_usage_intensity:
  type: str
  option: true
secret_modifications:
  type: str
  option: true
