dim_name: GoalsDim
short_term_goal:
  type: str
long_term_goal:
  type: str
motivation:
  type: str
survive_carol_harassment:
  type: str
  option: true
protect_muggleborn_friends:
  type: str
  option: true
gather_intelligence_on_death_eaters:
  type: str
  option: true
rebuild_dumbledores_army:
  type: str
  option: true
sabotage_carol_reign:
  type: str
  option: true
find_horcrux_information:
  type: str
  option: true
