dim_name: IdentityDim
id:
  type: str
name:
  type: str
role:
  type: str
blood_status:
  type: str
  option: true
faction:
  type: str
  option: true
public_role:
  type: str
  option: true
secret_role:
  type: str
  option: true
house:
  type: str
  option: true
year:
  type: str
  option: true
