dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
witnessed_cruciatus_cast:
  type: str
  option: true
attended_secret_da_meeting:
  type: str
  option: true
knows_room_of_requirement_location:
  type: str
  option: true
carried_messages_for_order:
  type: str
  option: true
hidden_muggleborn_escape_route:
  type: str
  option: true
