dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
current_hiding_status:
  type: str
  option: true
under_surveillance_flag:
  type: str
  option: true
injury_level:
  type: str
  option: true
polyjuice_disguise_active:
  type: str
  option: true
last_safe_room_visited:
  type: str
  option: true
