dim_name: CapabilitiesDim
skills:
  type: list_str
level:
  type: str
weaknesses:
  type: str
combat_style:
  type: str
  option: true
unique_ability:
  type: str
  option: true
magic_items:
  type: str
  option: true
power_source:
  type: str
  option: true
