dim_name: SocialProfileDim
group_id:
  type: str
  ref: institution
reputation:
  type: str
faction_role:
  type: str
  option: true
rebel_reputation:
  type: str
  option: true
faction_loyalty:
  type: str
  option: true
