dim_name: MemoriesDim
knowledge:
  world_knowledge:
    type: list_str
  social_knowledge:
    type: list_str
background_summary:
  type: str
key_events:
  type: list_str
secrets:
  type: list_str
recent_incidents:
  type: str
  option: true
traumatic_memories:
  type: str
  option: true
biased_beliefs:
  type: str
  option: true
superstitious_knowledge:
  type: str
  option: true
family_lore:
  type: str
  option: true
