dim_name: StateDim
location:
  location_id:
    type: str
    ref: location
position:
  x:
    type: float
  y:
    type: float
health_state:
  type: str
  option: true
current_action:
  type: str
  option: true
possession:
  type: str
  option: true
injury_status:
  type: str
  option: true
confinement_status:
  type: str
  option: true
