dim_name: EdgeDim
id:
  type: str
from_id:
  type: str
to_id:
  type: str
type:
  type: str
direction:
  type: str
is_secret:
  type: str
  option: true
is_violent:
  type: str
  option: true
control_type:
  type: str
  option: true
cooperation_type:
  type: str
  option: true
has_soul_correspondence:
  type: str
  option: true
