dim_name: PropertiesDim
strength:
  type: str
description:
  type: str
loyalty_dynamic:
  type: str
  option: true
trust_level:
  type: str
  option: true
fear_factor:
  type: str
  option: true
hidden_motive:
  type: str
  option: true
contact_frequency:
  type: str
  option: true
