dim_name: ConditionsDim
access_level:
  type: str
danger_level:
  type: str
required_items:
  type: str
curfew_restricted:
  type: str
  option: true
requires_password:
  type: str
  option: true
has_booby_trap:
  type: str
  option: true
alert_level:
  type: str
  option: true
requires_invisibility_cloak:
  type: str
  option: true
dementor_patrolled:
  type: str
  option: true
