dim_name: StateDim
current_state:
  type: str
ownership:
  type: str
capacity:
  type: int
fortification_level:
  type: str
  option: true
resource_richness:
  type: str
  option: true
population:
  type: str
  option: true
morale:
  type: str
  option: true
supply_level:
  type: str
  option: true
